"""Seeds a freshly-started agent with 15 realistic mock job rows.

Called once from POST /api/agent/start so the dashboard has data to show
immediately without waiting for a real scraping/scoring pipeline.
"""

import json
import uuid
from datetime import datetime, timedelta, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from models.models import Job


async def seed_mock_jobs(db: AsyncSession, agent_id: str):
    """Insert 15 realistic mock jobs for a new agent."""

    now = datetime.now(timezone.utc)

    def hours_ago(h):
        return (now - timedelta(hours=h)).isoformat()

    mock_jobs = [
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Senior Backend Engineer",
            "company": "Stripe",
            "description_summary": "Build and scale payment infrastructure handling millions of transactions daily. Work with Python, Go, and distributed systems at massive scale.",
            "salary_min": 160000,
            "salary_max": 210000,
            "work_mode": "Remote",
            "location": None,
            "apply_url": "https://linkedin.com/jobs/view/001",
            "match_score": 97,
            "match_reason": "Direct match on Python, FastAPI, and distributed systems experience.",
            "source": "LinkedIn",
            "tags": json.dumps(["Python", "Go", "PostgreSQL", "Redis", "Kafka"]),
            "posted_at": datetime.fromisoformat(hours_ago(2)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Full Stack Developer",
            "company": "Notion",
            "description_summary": "Join the product team building the next generation of Notion's web editor. Strong React and Node.js skills required.",
            "salary_min": 140000,
            "salary_max": 180000,
            "work_mode": "Hybrid",
            "location": "San Francisco, CA",
            "apply_url": "https://linkedin.com/jobs/view/002",
            "match_score": 95,
            "match_reason": "Strong alignment on React.js, TypeScript, and full-stack architecture.",
            "source": "LinkedIn",
            "tags": json.dumps(["React", "TypeScript", "Node.js", "PostgreSQL", "AWS"]),
            "posted_at": datetime.fromisoformat(hours_ago(3)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Senior Python Developer",
            "company": "Datadog",
            "description_summary": "Develop high-performance data ingestion pipelines processing billions of metrics per day. Work with Python, Kafka, and Kubernetes.",
            "salary_min": 155000,
            "salary_max": 200000,
            "work_mode": "Remote",
            "location": None,
            "apply_url": "https://indeed.com/jobs/view/003",
            "match_score": 93,
            "match_reason": "Python expertise and Docker/Kubernetes experience are a strong match.",
            "source": "Indeed",
            "tags": json.dumps(["Python", "Kafka", "Kubernetes", "Docker", "Redis"]),
            "posted_at": datetime.fromisoformat(hours_ago(4)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "DevOps Engineer",
            "company": "HashiCorp",
            "description_summary": "Design and maintain CI/CD pipelines and cloud infrastructure across AWS and GCP. Terraform and Kubernetes expertise required.",
            "salary_min": 145000,
            "salary_max": 185000,
            "work_mode": "Remote",
            "location": None,
            "apply_url": "https://glassdoor.com/jobs/view/004",
            "match_score": 89,
            "match_reason": "Docker and AWS experience align well with the infrastructure requirements.",
            "source": "Glassdoor",
            "tags": json.dumps(["Terraform", "Kubernetes", "AWS", "Docker", "CI/CD"]),
            "posted_at": datetime.fromisoformat(hours_ago(5)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Platform Engineer",
            "company": "Airbnb",
            "description_summary": "Build internal developer platforms and tooling to improve engineering velocity across 5,000 engineers.",
            "salary_min": 170000,
            "salary_max": 220000,
            "work_mode": "Onsite",
            "location": "San Francisco, CA",
            "apply_url": "https://linkedin.com/jobs/view/005",
            "match_score": 88,
            "match_reason": "Backend engineering background and Python skills match platform requirements.",
            "source": "LinkedIn",
            "tags": json.dumps(["Python", "Kubernetes", "AWS", "Go", "Terraform"]),
            "posted_at": datetime.fromisoformat(hours_ago(6)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "ML Engineer",
            "company": "OpenAI",
            "description_summary": "Train and deploy large language models at scale. Work on the infrastructure that powers cutting-edge AI products.",
            "salary_min": 200000,
            "salary_max": 300000,
            "work_mode": "Onsite",
            "location": "San Francisco, CA",
            "apply_url": "https://indeed.com/jobs/view/006",
            "match_score": 82,
            "match_reason": "Python and FastAPI experience are relevant; ML specialization would strengthen fit.",
            "source": "Indeed",
            "tags": json.dumps(["Python", "PyTorch", "CUDA", "Kubernetes", "Distributed Training"]),
            "posted_at": datetime.fromisoformat(hours_ago(7)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Cloud Architect",
            "company": "Snowflake",
            "description_summary": "Architect multi-region cloud infrastructure solutions for enterprise data warehouse clients on AWS and Azure.",
            "salary_min": 180000,
            "salary_max": 240000,
            "work_mode": "Hybrid",
            "location": "New York, NY",
            "apply_url": "https://linkedin.com/jobs/view/007",
            "match_score": 80,
            "match_reason": "AWS and Docker experience are a foundation; cloud architecture depth would help.",
            "source": "LinkedIn",
            "tags": json.dumps(["AWS", "Azure", "Terraform", "Python", "Networking"]),
            "posted_at": datetime.fromisoformat(hours_ago(8)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Data Engineer",
            "company": "Spotify",
            "description_summary": "Build and maintain data pipelines processing listening data from 600 million users. Work with Spark, Kafka, and BigQuery.",
            "salary_min": 140000,
            "salary_max": 175000,
            "work_mode": "Hybrid",
            "location": "New York, NY",
            "apply_url": "https://glassdoor.com/jobs/view/008",
            "match_score": 79,
            "match_reason": "Python and PostgreSQL skills transfer well to data engineering pipelines.",
            "source": "Glassdoor",
            "tags": json.dumps(["Python", "Spark", "Kafka", "BigQuery", "Airflow"]),
            "posted_at": datetime.fromisoformat(hours_ago(9)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Site Reliability Engineer",
            "company": "GitHub",
            "description_summary": "Ensure the reliability and performance of GitHub infrastructure serving 100 million developers worldwide.",
            "salary_min": 155000,
            "salary_max": 195000,
            "work_mode": "Remote",
            "location": None,
            "apply_url": "https://indeed.com/jobs/view/009",
            "match_score": 78,
            "match_reason": "Docker and AWS experience align with SRE infrastructure requirements.",
            "source": "Indeed",
            "tags": json.dumps(["Go", "Kubernetes", "Prometheus", "AWS", "Python"]),
            "posted_at": datetime.fromisoformat(hours_ago(10)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "API Engineer",
            "company": "Twilio",
            "description_summary": "Design and build public-facing APIs consumed by millions of developers. FastAPI and REST design expertise required.",
            "salary_min": 130000,
            "salary_max": 165000,
            "work_mode": "Remote",
            "location": None,
            "apply_url": "https://linkedin.com/jobs/view/010",
            "match_score": 94,
            "match_reason": "FastAPI and REST API experience are a direct and strong match for this role.",
            "source": "LinkedIn",
            "tags": json.dumps(["FastAPI", "Python", "PostgreSQL", "Redis", "Docker"]),
            "posted_at": datetime.fromisoformat(hours_ago(11)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "React Developer",
            "company": "Figma",
            "description_summary": "Build the next generation of Figma's browser-based design tools. Deep React and WebGL knowledge required.",
            "salary_min": 145000,
            "salary_max": 185000,
            "work_mode": "Onsite",
            "location": "San Francisco, CA",
            "apply_url": "https://glassdoor.com/jobs/view/011",
            "match_score": 86,
            "match_reason": "React.js and TypeScript experience align well with frontend requirements.",
            "source": "Glassdoor",
            "tags": json.dumps(["React", "TypeScript", "WebGL", "GraphQL", "CSS"]),
            "posted_at": datetime.fromisoformat(hours_ago(12)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Software Engineer II",
            "company": "Shopify",
            "description_summary": "Work on Shopify's core commerce platform serving 2 million merchants globally. Ruby on Rails and React experience preferred.",
            "salary_min": 120000,
            "salary_max": 155000,
            "work_mode": "Hybrid",
            "location": "Austin, TX",
            "apply_url": "https://indeed.com/jobs/view/012",
            "match_score": 74,
            "match_reason": "Full-stack experience and PostgreSQL skills are transferable to this role.",
            "source": "Indeed",
            "tags": json.dumps(["Ruby", "React", "PostgreSQL", "Docker", "GraphQL"]),
            "posted_at": datetime.fromisoformat(hours_ago(13)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Infrastructure Engineer",
            "company": "Cloudflare",
            "description_summary": "Build and operate global network infrastructure running at 200 edge locations. Networking and Linux systems expertise required.",
            "salary_min": 150000,
            "salary_max": 190000,
            "work_mode": "Onsite",
            "location": "Austin, TX",
            "apply_url": "https://linkedin.com/jobs/view/013",
            "match_score": 70,
            "match_reason": "Docker and AWS experience provide a relevant infrastructure foundation.",
            "source": "LinkedIn",
            "tags": json.dumps(["Linux", "Networking", "Go", "Rust", "Kubernetes"]),
            "posted_at": datetime.fromisoformat(hours_ago(14)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Senior TypeScript Engineer",
            "company": "Vercel",
            "description_summary": "Shape the future of frontend development tooling. Work on Next.js, edge runtimes, and the Vercel platform.",
            "salary_min": None,
            "salary_max": None,
            "work_mode": "Remote",
            "location": None,
            "apply_url": "https://glassdoor.com/jobs/view/014",
            "match_score": 83,
            "match_reason": "TypeScript and React experience align well with Vercel's frontend platform work.",
            "source": "Glassdoor",
            "tags": json.dumps(["TypeScript", "React", "Next.js", "Node.js", "Edge Runtime"]),
            "posted_at": datetime.fromisoformat(hours_ago(16)),
            "found_at": now,
        },
        {
            "id": str(uuid.uuid4()),
            "agent_id": agent_id,
            "title": "Solutions Architect",
            "company": "AWS",
            "description_summary": "Guide enterprise customers through complex cloud migrations and architecture design on AWS. Strong communication and technical depth required.",
            "salary_min": None,
            "salary_max": None,
            "work_mode": "Hybrid",
            "location": "Seattle, WA",
            "apply_url": "https://indeed.com/jobs/view/015",
            "match_score": 67,
            "match_reason": "AWS and Docker experience are relevant; solutions architecture is a growth direction.",
            "source": "Indeed",
            "tags": json.dumps(["AWS", "Cloud Architecture", "Python", "Terraform", "Networking"]),
            "posted_at": datetime.fromisoformat(hours_ago(20)),
            "found_at": now,
        },
    ]

    for job_data in mock_jobs:
        job = Job(**job_data)
        db.add(job)

    await db.flush()
